services:
  db_mysql:
    image: mysql
    container_name: db_mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_config:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: **
      MYSQL_DATABASE: cornmarket
      MYSQL_USER: hice
      MYSQL_PASSWORD: **
    ports:
      - '3307:3306'
volumes:
  mysql_data:
